-- Auto-generated EmmyLua annotations from SOL2 registrations
-- Generated by sol2_to_emmylua.py
-- Source files processed:
--   src/engine.h
--   src/glad/KHR/khrplatform.h
--   src/glad/glad.cpp
--   src/glad/glad.h
--   src/include/colors.h
--   src/include/imgui/imgui.cpp
--   src/include/imgui/imgui.h
--   src/include/imgui/imgui_demo.cpp
--   src/include/imgui/imgui_draw.cpp
--   src/include/imgui/imgui_impl_glfw.cpp
--   src/include/imgui/imgui_impl_glfw.h
--   src/include/imgui/imgui_impl_opengl3.cpp
--   src/include/imgui/imgui_impl_opengl3.h
--   src/include/imgui/imgui_impl_opengl3_loader.h
--   src/include/imgui/imgui_internal.h
--   src/include/imgui/imgui_tables.cpp
--   src/include/imgui/imgui_widgets.cpp
--   src/include/imgui/imstb_rectpack.h
--   src/include/imgui/imstb_textedit.h
--   src/include/imgui/imstb_truetype.h
--   src/include/stbi_image.h
--   src/lua/class/camera.cpp
--   src/lua/class/camera.h
--   src/lua/class/color.cpp
--   src/lua/class/color.h
--   src/lua/class/font.cpp
--   src/lua/class/font.h
--   src/lua/class/gizmo.cpp
--   src/lua/class/gizmo.h
--   src/lua/class/image.cpp
--   src/lua/class/image.h
--   src/lua/class/input.cpp
--   src/lua/class/input.h
--   src/lua/class/mesh.cpp
--   src/lua/class/mesh.h
--   src/lua/class/rt/mesh_tbo.cpp
--   src/lua/class/rt/mesh_tbo.h
--   src/lua/class/rt/sphere_tbo.cpp
--   src/lua/class/rt/sphere_tbo.h
--   src/lua/class/rt/tbo.cpp
--   src/lua/class/rt/tbo.h
--   src/lua/class/shader.cpp
--   src/lua/class/shader.h
--   src/lua/class/signal.cpp
--   src/lua/class/signal.h
--   src/lua/class/template.cpp
--   src/lua/class/template.h
--   src/lua/class/textlabel.cpp
--   src/lua/class/textlabel.h
--   src/lua/class/vfx.cpp
--   src/lua/class/vfx.h
--   src/lua/lua.cpp
--   src/lua/lua.h
--   src/lua/luax.cpp
--   src/lua/luax.h
--   src/lua/module/lua_font.cpp
--   src/lua/module/lua_font.h
--   src/lua/module/lua_opengl_constants.cpp
--   src/lua/module/lua_opengl_constants.h
--   src/lua/module/lua_rendering.cpp
--   src/lua/module/lua_rendering.h
--   src/lua/module/lua_ui.cpp
--   src/lua/module/lua_ui.h
--   src/lua/module/lua_window.cpp
--   src/lua/module/lua_window.h
--   src/main.cpp
--   src/opengl/freetype.cpp
--   src/opengl/freetype.h
--   src/opengl/shader.cpp
--   src/opengl/shader.h
--   src/opengl/vfx_effect.cpp
--   src/opengl/vfx_effect.h
--   src/opengl/window.cpp
--   src/opengl/window.h

-- Source: camera.cpp
---@class BSGECameraMetadata Camera type for LuaBSGE
---@field fov number Field of view in degrees (default: 70.0)
---@field near_clip number Near clipping plane distance (default: 0.1)
---@field far_clip number Far clipping plane distance (default: 100.0)
---@field matrix table 4x4 transformation matrix (glm::mat4)
---@field get_projection_matrix returns perspective matrix 
BSGECameraMetadata = {}

---Method fov
---@return any
function BSGECameraMetadata:fov() end

---Method near_clip
---@return any
function BSGECameraMetadata:near_clip() end

---Method far_clip
---@return any
function BSGECameraMetadata:far_clip() end

---Method matrix
---@return any
function BSGECameraMetadata:matrix() end

_G.BSGECameraMetadata = BSGECameraMetadata

-- Source: font.cpp
---@class Font Font type for LuaBSGE
Font = {}

_G.Font = Font

-- Source: image.cpp
---@class bsgeImage bsgeImage type for LuaBSGE
bsgeImage = {}

_G.bsgeImage = bsgeImage

-- Source: mesh.cpp
---@class meshData meshData type for LuaBSGE
meshData = {}

_G.meshData = meshData

-- Source: mesh_tbo.cpp
---@class MeshBufferObject MeshBufferObject type for LuaBSGE
MeshBufferObject = {}

_G.MeshBufferObject = MeshBufferObject

-- Source: sphere_tbo.cpp
---@class SphereBufferObject SphereBufferObject type for LuaBSGE
SphereBufferObject = {}

_G.SphereBufferObject = SphereBufferObject

-- Source: shader.cpp
---@class ShaderStruct ShaderStruct type for LuaBSGE
ShaderStruct = {}

_G.ShaderStruct = ShaderStruct

-- Source: template.cpp
---@class TemplateStruct TemplateStruct type for LuaBSGE
TemplateStruct = {}

---Method function_calls
---@return any
function TemplateStruct:function_calls() end

_G.TemplateStruct = TemplateStruct

-- Source: textlabel.cpp
---@class Textlabel Textlabel type for LuaBSGE
Textlabel = {}

---Method color
---@return any
function Textlabel:color() end

---Method position
---@return any
function Textlabel:position() end

---Method anchor
---@return any
function Textlabel:anchor() end

---Method scale
---@return any
function Textlabel:scale() end

---Method font
---@return any
function Textlabel:font() end

_G.Textlabel = Textlabel

-- Source: vfx.cpp
---@class VFXEffectStruct VFXEffectStruct type for LuaBSGE
VFXEffectStruct = {}

---Method is_valid
---@return any
function VFXEffectStruct:is_valid() end

_G.VFXEffectStruct = VFXEffectStruct
