#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform sampler2D displayTexture;
layout(set = 0, binding = 1) uniform sampler2D depthTexture;
layout(set = 0, binding = 2, rgba16f) uniform writeonly image2D outImage;

struct DirectionalLight {
    vec4 direction;
    vec4 color;
};

struct PointLight {
    vec4 position;
    vec4 color;
};

layout(set = 0, binding = 3, std430) readonly buffer Lights {
    DirectionalLight lights[];
};

layout(set = 0, binding = 4, std430) readonly buffer PointLights {
    PointLight point_lights[];
};

layout(push_constant) uniform constants {
    int light_count;
    int point_light_count;
} PushConstants;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(outImage);
    if (coord.x >= size.x || coord.y >= size.y) return;

    vec2 uv = (vec2(coord) + 0.5) / vec2(size);
    vec3 albedo = texture(displayTexture, uv).rgb;

    vec3 lighting = vec3(0.0);
    if (PushConstants.light_count == 0 && PushConstants.point_light_count == 0) {
        lighting = vec3(0.0);
    } else {
        for (int i = 0; i < PushConstants.light_count; i++) {
            lighting += lights[i].color.rgb / 1000000.0;
        }

        for (int i = 0; i < PushConstants.point_light_count; i++) {
            lighting += point_lights[i].color.rgb / 1000000.0;
        }
    }

    imageStore(outImage, coord, vec4(albedo , 1.0));
}
